// This module re-exports auto-generated ROS message types
// The actual code is generated at build time and included from OUT_DIR

// Include the CDR-compatible generated code (serde-based)
include!(concat!(env!("OUT_DIR"), "/generated.rs"));

// Accurate size estimation for SHM serialization (trait + primitives)
// Implementations for ROS messages are auto-generated by hiroz-codegen
pub mod size_estimation;

// Re-export the namespaced modules for compatibility
pub use self::ros::*;

/// Comma-separated ROS package names this build actually generated code
/// for -- `build.rs`'s real `selected_package_names`/`discover_ros_packages`
/// output, embedded via `cargo:rustc-env` at build time. Lets tests assert
/// on which packages a given feature set produced without needing to name
/// every generated type. See `tests/feature_scoping.rs`.
pub const GENERATED_PACKAGES: &str = env!("HIROZ_MSGS_GENERATED_PACKAGES");

// Include the protobuf-compatible generated code (prost-based) if feature is enabled
#[cfg(feature = "protobuf")]
pub mod proto {
    //! Protobuf-serializable message types
    //!
    //! These types are compatible with `hiroz::msg::ProtobufSerdes` and can be used
    //! for protobuf serialization instead of CDR.
    //!
    //! # Example
    //! ```no_run
    //! use hiroz_msgs::proto::geometry_msgs::Vector3;
    //! use hiroz::msg::ProtobufSerdes;
    //!
    //! let vec = Vector3 { x: 1.0, y: 2.0, z: 3.0 };
    //! // Use with .with_serdes::<ProtobufSerdes<Vector3>>()
    //! ```

    include!(concat!(env!("OUT_DIR"), "/generated_proto.rs"));
}

// Include the protobuf type info implementations if feature is enabled
#[cfg(feature = "protobuf")]
include!(concat!(env!("OUT_DIR"), "/protobuf_type_info.rs"));

#[cfg(not(feature = "protobuf"))]
pub mod proto {
    //! Placeholder module when protobuf feature is not enabled
}

// Include generated Python bindings (complete module)
#[cfg(feature = "python_registry")]
include!(concat!(env!("OUT_DIR"), "/python_bindings.rs"));

// Re-export commonly used items from hiroz for convenience
pub use hiroz::{
    MessageTypeInfo,
    entity::{TypeHash, TypeInfo},
};
